import React, { useState, useEffect } from 'react';
import { instructorService } from '../../services/instructorService';
import { useToast } from '../../context/ToastContext';
import SkeletonLoader from '../../components/common/SkeletonLoader';
import EmptyState from '../../components/common/EmptyState';
import ErrorState from '../../components/common/ErrorState';
import { FileSpreadsheet, Download, FileText, PlusCircle } from 'lucide-react';

export const ReportsPage = () => {
  const { addToast } = useToast();
  const [projects, setProjects] = useState([]);
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [selectedProject, setSelectedProject] = useState('All');

  const fetchReportsData = async () => {
    setLoading(true);
    setError(null);
    try {
      const projs = await instructorService.getProjects();
      setProjects(Array.isArray(projs) ? projs : []);
      const reps = await instructorService.getReports();
      setReports(Array.isArray(reps) ? reps : []);
    } catch (err) {
      setError(err.message || 'Unable to retrieve course reports.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchReportsData();
  }, []);

  const handleGenerateReport = async (reportType) => {
    try {
      const newRep = await instructorService.generateReport(reportType);
      setReports((prev) => [newRep, ...prev]);
      addToast(`Generated ${reportType} report successfully!`, 'success');
    } catch (err) {
      addToast('Failed to generate report.', 'error');
    }
  };

  if (loading) {
    return (
      <div className="p-4 sm:p-6 lg:p-8 max-w-7xl mx-auto space-y-4">
        <SkeletonLoader count={3} height="h-32" />
      </div>
    );
  }

  if (error) {
    return (
      <div className="p-4 sm:p-6 lg:p-8 max-w-7xl mx-auto">
        <ErrorState title="Unable to load reports" message={error} onRetry={fetchReportsData} />
      </div>
    );
  }

  const reportTemplates = [
    { title: 'Student Collaboration Report', desc: 'Individual contribution breakdown per student based on recorded activity.' },
    { title: 'Group Performance Report', desc: 'Comparative group metrics evaluating work distribution and milestone completion.' },
    { title: 'Project Summary Report', desc: 'Complete course project progress, tasks completed, and score summary.' },
    { title: 'AI Grading & Evaluation Report', desc: 'Academic evaluation report generated by AI grading engine.' }
  ];

  return (
    <div className="p-4 sm:p-6 lg:p-8 max-w-7xl mx-auto space-y-8">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-white p-6 rounded-3xl border border-slate-200/80 shadow-xs">
        <div>
          <h1 className="text-2xl font-black text-slate-900 tracking-tight flex items-center gap-2">
            <FileSpreadsheet className="w-6 h-6 text-indigo-600" />
            Reports & Export Center
          </h1>
          <p className="text-xs text-slate-500 mt-1">
            Generate and export official academic reports based on actual database collaboration data.
          </p>
        </div>
      </div>

      {projects.length === 0 && reports.length === 0 ? (
        <EmptyState
          icon={FileSpreadsheet}
          title="No Reports Available"
          message="Reports will become available after collaboration data has been collected."
          actionLabel="Refresh Reports"
          onAction={fetchReportsData}
        />
      ) : (
        <>
          {/* Action Generator Cards */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {reportTemplates.map((template, idx) => (
              <div key={idx} className="bg-white rounded-3xl p-6 border border-slate-200/80 shadow-xs flex flex-col justify-between">
                <div>
                  <h3 className="text-base font-bold text-slate-900 mb-2">{template.title}</h3>
                  <p className="text-xs text-slate-500 leading-relaxed mb-6">{template.desc}</p>
                </div>

                <div className="pt-4 border-t border-slate-100 flex items-center justify-end gap-2">
                  <button
                    onClick={() => handleGenerateReport(template.title)}
                    className="px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-bold rounded-xl shadow-xs transition-colors flex items-center gap-1.5"
                  >
                    <PlusCircle className="w-3.5 h-3.5" />
                    <span>Generate Report</span>
                  </button>
                </div>
              </div>
            ))}
          </div>

          {/* Generated Reports List */}
          {reports.length > 0 && (
            <div className="bg-white rounded-3xl p-6 border border-slate-200/80 shadow-xs space-y-4">
              <h3 className="text-base font-extrabold text-slate-900">Generated Report Archive</h3>

              <div className="divide-y divide-slate-100 text-xs">
                {reports.map((rep) => (
                  <div key={rep.id} className="py-3 flex items-center justify-between">
                    <div>
                      <span className="font-bold text-slate-900 block">{rep.name}</span>
                      <span className="text-[10px] text-slate-400">Generated: {rep.generatedAt}</span>
                    </div>

                    <div className="flex items-center gap-2">
                      <span className="px-2.5 py-0.5 bg-slate-100 text-slate-600 font-bold rounded-md text-[10px]">
                        {rep.type || 'PDF'}
                      </span>
                      <button
                        onClick={() => addToast(`Downloaded ${rep.name}`, 'success')}
                        className="p-1.5 bg-indigo-50 text-indigo-600 hover:bg-indigo-100 rounded-lg font-bold"
                        title="Download"
                      >
                        <Download className="w-4 h-4" />
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </>
      )}
    </div>
  );
};

export default ReportsPage;
