import React from 'react';
import { Brain, MessageSquare, TrendingUp, Target, Sparkles, CheckCircle2 } from 'lucide-react';

const iconMap = {
  Brain,
  MessageSquare,
  TrendingUp,
  Target
};

export const AIInsightCard = ({ category, title, description, badge, color = 'blue', iconName = 'Brain' }) => {
  const IconComponent = iconMap[iconName] || Brain;

  const themeClasses = {
    blue: {
      bg: 'bg-blue-50/50',
      border: 'border-blue-200/80',
      iconBg: 'bg-blue-100 text-blue-600',
      badgeBg: 'bg-blue-100 text-blue-800 border-blue-200',
    },
    indigo: {
      bg: 'bg-indigo-50/50',
      border: 'border-indigo-200/80',
      iconBg: 'bg-indigo-100 text-indigo-600',
      badgeBg: 'bg-indigo-100 text-indigo-800 border-indigo-200',
    },
    emerald: {
      bg: 'bg-emerald-50/50',
      border: 'border-emerald-200/80',
      iconBg: 'bg-emerald-100 text-emerald-600',
      badgeBg: 'bg-emerald-100 text-emerald-800 border-emerald-200',
    },
    amber: {
      bg: 'bg-amber-50/50',
      border: 'border-amber-200/80',
      iconBg: 'bg-amber-100 text-amber-600',
      badgeBg: 'bg-amber-100 text-amber-800 border-amber-200',
    },
  };

  const theme = themeClasses[color] || themeClasses.blue;

  return (
    <div className={`rounded-2xl p-5 border ${theme.bg} ${theme.border} shadow-xs hover:shadow-md transition-all duration-300 flex flex-col justify-between`}>
      <div>
        <div className="flex items-center justify-between mb-3">
          <div className="flex items-center gap-2">
            <div className={`p-2.5 rounded-xl ${theme.iconBg}`}>
              <IconComponent className="w-4 h-4" />
            </div>
            <span className="text-xs font-bold uppercase tracking-wider text-slate-500">{category}</span>
          </div>
          {badge && (
            <span className={`px-2.5 py-0.5 rounded-full text-[11px] font-bold border ${theme.badgeBg}`}>
              {badge}
            </span>
          )}
        </div>
        <h4 className="text-base font-bold text-slate-900 mb-1.5">{title}</h4>
        <p className="text-xs text-slate-600 leading-relaxed">{description}</p>
      </div>

      <div className="mt-4 pt-3 border-t border-slate-200/50 flex items-center gap-1.5 text-[11px] font-semibold text-indigo-700">
        <Sparkles className="w-3.5 h-3.5" />
        <span>Generated by Collab Track AI Engine v2.4</span>
      </div>
    </div>
  );
};

export default AIInsightCard;
